export const MINUTES_IN_DAY = 60*24
export const MINUTE_INTERVAL = 5
export const MINUTE_INTERVALS_PER_DAY = MINUTES_IN_DAY / MINUTE_INTERVAL

export const MINUTE_TICK_PX_WIDTH = 1
export const MINUTE_SPACE_PX_WIDTH = 10

export const MINUTE_TICK_PX_HEIGHT = 10
export const QUARTER_HOUR_TICK_PX_HEIGHT = 15
export const HOUR_TICK_PX_HEIGHT = 25

export const TIME_LABEL_PX_WIDTH = 40
export const TIME_LABEL_MINUTE_INTERVAL = 30

export const TIME_LINE_PX_WIDTH = 1

export const DAY_BAR_PX_WIDTH = (
    MINUTE_INTERVALS_PER_DAY
    * (MINUTE_TICK_PX_WIDTH + MINUTE_SPACE_PX_WIDTH)
    - MINUTE_SPACE_PX_WIDTH
)
